import type { Rule } from "./types";
import { findPhrases } from "./text";

/** Words that let two readers picture two different things. Value = the question a reader asks. */
export const VAGUE: Record<string, string> = {
  some: "How many, exactly?",
  several: "How many, exactly?",
  many: "How many?",
  few: "How many?",
  various: "Which ones?",
  soon: "Within what time?",
  quickly: "How fast? Give a number.",
  fast: "How fast? Give a number.",
  slow: "How slow? Give a number.",
  promptly: "Within what time?",
  timely: "By when?",
  "as soon as possible": "By when?",
  asap: "By when?",
  recently: "Since when?",
  recent: "Since when?",
  appropriate: "Appropriate by whose rule?",
  appropriately: "By whose rule?",
  adequate: "What counts as adequate?",
  sufficient: "How much is enough?",
  reasonable: "Reasonable by whose rule?",
  "as needed": "Who decides it is needed?",
  "if necessary": "Who decides it is necessary, and how?",
  "if needed": "Who decides it is needed?",
  "where possible": "When is it not possible?",
  "and so on": "What else, exactly?",
  etc: "What else, exactly?",
  usually: "And when not?",
  normally: "And when not?",
  often: "How often?",
  sometimes: "When, exactly?",
  "user-friendly": "What should the user be able to do?",
  easy: "Easy for whom, measured how?",
  simple: "Simple how?",
  efficient: "Measured how?",
  robust: "Survives what, exactly?",
  flexible: "Changes in which ways?",
  large: "How large?",
  small: "How small?",
  significant: "How big is significant?",
  relevant: "Relevant by what test?",
  minimal: "How little?",
  optimal: "Optimal by what measure?",
  periodically: "How often?",
  regularly: "How often?",
  approximately: "Within what tolerance?",
  "a while": "How long?",
  "a bit": "How much?",
  "a lot": "How much?",
};

export const vagueWords: Rule = (text) =>
  findPhrases(text, Object.keys(VAGUE)).map((h) => ({
    ruleId: "vagueWords" as const,
    severity: "warn" as const,
    start: h.start,
    end: h.end,
    message: `"${text.slice(h.start, h.end)}" is vague. ${VAGUE[h.phrase]}`,
    suggestion: "Replace it with a number, a name, or a test anyone can check.",
  }));
